# Generated by Django 4.2.7 on 2023-11-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.BigIntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=20)),
                ('aprobado', models.BooleanField(default=False)),
            ],
        ),
    ]
